name: Ayushman Devraj
tagline: Literary Scholar and Educator
career-objective: <strong>Welcome to my personal homepage!</strong> <br> <br> Here, you can explore my academic journey, research interests, and professional achievements. Stay updated with my latest publications and projects in the field of English literature and cultural studies. 
color-theme: red # red or blue
avatar-filename: avatar.jpg # Change to your avatar's filename
url: devraj.net.in
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: adevraj@rgu.ac
  github: 
    visibility: false
    handle: arnobk
  linkedin: 
    visibility: true
    handle: aydevraj
  twitter: 
    visibility: true
    handle: aydevraj

# Collections
collections:
  experience:
    output: true
    sort_by: order
  education:
    output: true
    sort_by: order
  projects:
    output: false
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: true
    sort_by: year
  achievements:
    output: true
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Internship
    visibility: true
  publications: 
    label: Publications (update in process)
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Academic Engagements (recent five)
    visibility: true
  achievements: 
    label: Award/Fellowship
    visibility: true

navigation:
- title: About
  url: /
- title: Posts
  url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname:  # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint:  # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X